### ISSUE TITLE
🚚 Rename the repo

### ISSUE THREAD

**Issue by ewjoachim** [sphinx-contrib/sphinxcontrib-towncrier#5]
Hey there :) long time no see :p

I know we [already](https://twitter.com/Ewjoachim/status/1289659861995724800?s=20) kinda had this discussion, but the more I dig into it the more pressing the issue is.

Arguments for renaming:
- You can't clone both this towncrier and the other towncrier locally without renaming one of them
- If you try forking both on GitHub... Not even sure you can.
- If I say "towncrier" in the issues or PRs of this repo, it's suddenly unclear whether I'm speaking about towncrier or towncrier.
- People might find this repo on Google while looking for towncrier. And if they don't really know what sphinx is, good luck for understanding what mess they're in.

Arguments for keeping (I'm probably missing many):
- Github full slug "sphinx-contrib/towncrier" mentions that it's sphinx-related
- sphinx-contrib repos are not supposed to be "sphinx-" something

Propositions:
- towncrier-directive
- towncrier-draft
- towncrier-integration
- towncrier-extension
- towncrier-ext
- towncrier-actually-whatever-as-long-as-it's-not-just-towncrier-:p

**Comment by ewjoachim** [comment]
Tuns out you can fork both, but the second is renamed `-1`. This itself should be smelly enough to know something's not quite right.
<img width="301" alt="Capture d’écran 2020-08-03 à 22 46 13" src="https://user-images.githubusercontent.com/1457576/89225881-44f9d800-d5db-11ea-8576-f38ec757f83d.png">

**Comment by webknjaz** [comment]
Thanks for filing this, Joachim!

I'm having mixed feelings about this and I totally hear all of the pros and cons you've outlined here.
I'm still leaning towards keeping it as is. FTR I'm least opposed to the ext/extension suffixes among the suggested alternatives.

But in the spirit of transparency and having an open discussion, let's invite others active on that Twitter thread and in the org to have them share their opinions.

@gaborbernat @nicoddemus @gundalow @RonnyPfannschmidt @hawkowl do any of you have opinions on how this repository should be called? The current name is motivated by the mapping of the target PyPI project name `sphinxcontrib-towncrier` to the full GitHub slug `sphinx-contrib/towncrier`. The part after the slash is not prefixed with anything pointing to sphinx because of the convention outlined @ https://github.com/sphinx-contrib/github-administration#how-do-i-add-a-new-repo-to-sphinx-contrib.

**Comment by gaborbernat** [comment]
IMHO sphinx-towncrier 🤷‍♂️

**Comment by webknjaz** [comment]
> I don't see much benefit in living under sphinxcontrib org

I don't want to keep it under a personal profile. So it's the best solution + gives a bit more visibility.

**Comment by nicoddemus** [comment]
> IMHO sphinx-towncrier

I second that... that definitely would be my google search for a sphinx towncrier plugin. 😁

**Comment by webknjaz** [comment]
Oh, I also wanted to ping @dhellmann to check if making an exception would be fine.

**Comment by webknjaz** [comment]
> I second that... that definitely would be my google search for a sphinx towncrier plugin.

Funny, it's the first result for me already: https://www.google.com/search?q=sphinx-towncrier.

**Comment by nicoddemus** [comment]
> Funny, it's the first result for me already

Heh.

**Comment by dhellmann** [comment]
The "rule" about names, such as it is, was meant to introduce a bit of consistency. This case isn't something I really considered, so if it's causing a problem (and it seems it is), we should deal with that and not get caught up on process.

I can think of a couple of ways to address the issue. The first is the obvious renaming of this repo. I think I would go with `sphinxcontrib-towncrier` to match the PyPI dist name, but I don't have a strong opinion and would leave it up to the contributors to pick the name. I think anyone with admin on the repo can rename it, but as an org admin I can, too, so let me know if you want me to do that. If you choose to rename, I would appreciate it if someone took a minute to update the process doc with a little text to provide a caveat for cases like this and mention this as a precedent.

Before we do that, there is another option worth serious consideration: move the sphinx extension into the towncrier repository, and develop it together with the app. That has worked well in some other cases, since it means any breaking changes or new features in towncrier can be handled in the sphinx extension at the same time. On the other hand, it means that the contributors to the (today) two projects need to come to an agreement about commit rights, bug tracking, release processes, etc. I encourage you to explore the idea, and would be happy to point to a couple of other projects that could serve as examples of how to manage technical aspects like testing and dependencies.

So, I'm open to whatever you want to do.

**Comment by webknjaz** [comment]
Thanks @dhellmann, I think, I'll rename it. So to be clear the options I'm considering are `sphinx-contrib/towncrier-ext` and `sphinx-contrib/sphinxcontrib-towncrier`. The latter seems too long so my personal preference is the former. Unless somebody has a strong opinion on this, I'd prefer to use it (please vote!).


> Before we do that, there is another option worth serious consideration: move the sphinx extension into the towncrier repository, and develop it together with the app. That has worked well in some other cases, since it means any breaking changes or new features in towncrier can be handled in the sphinx extension at the same time.

I did consider this option, especially looking at what pbr does with reno (yeah, I know that it's not the same but still). But atm it doesn't seem like Towncrier is active enough. For example, there's a about 11 PRs that are in master but were never released. Based on the previous releases, I'd say that the average release cycle seems to be approximately 1.5 years. Also, I'm seeing the increasing number of issues and PRs that don't really get any attention.

This all makes me believe that keeping the extension there would be troublesome. It would probably mean taking over the maintenance (even partially), also it'll probably force us to comply with some release policies of Twisted. Besides, based on activity, the request to get something merged and maybe get maintenance privileges will probably only get some attention months after it's created.

OTOH having it separate will allow us to be free to do releases as we please. Right away. Even 20 releases a day if needed. From this point of view, being less tightly coupled with that repo is a good thing.

I do recognize the benefits of being a part of the monolithic repo, though. Like being always compatible. But it's not a big deal for us really, since we invoke towncrier CLI and it's very unlikely to break. Plus it's solvable by testing against their master continuously + capping the maximum runtime dependency version. There's a better chance of breaking Sphinx compat and then being blocked from fixing that by the repo inactivity, IMHO.

**Comment by webknjaz** [comment]
Alright, since nobody spoke up, I'm going to rename the repo to `sphinx-contrib/towncrier-ext` later today. The PyPI project name stays `sphinxcontrib-towncrier`.

**Comment by gaborbernat** [comment]
I strongly prefer matching the repository name with the pypi name.

**Comment by webknjaz** [comment]
@gaborbernat anything against `sphinxcontrib-towncrier-ext`, then?

**Comment by gaborbernat** [comment]
Why not make it one on one match with pypyi name?

**Comment by webknjaz** [comment]
It'd match as in `sphinxcontrib-towncrier-ext` -> `sphinx-contrib/towncrier-ext`

**Comment by gaborbernat** [comment]
🤷‍♂️ prefer exact matches, so up to you. I don't think sphinxcontrib adds anything in the name. 🤷‍♂️

**Comment by webknjaz** [comment]
Okay, I'll stop on `sphinx-contrib/sphinxcontrib-towncrier`, then. It should fit everybody's requests. The reason I didn't want the prefix in the repo is that the full slug would be long but I still want the prefix on PyPI.
