### ISSUE TITLE
🔥 Remove scm version fallbacks from the extension

### ISSUE THREAD

**Issue by ewjoachim** [sphinx-contrib/sphinxcontrib-towncrier#7]
(Just to make it clear, I'm talking about the runtime dependency to setuptools-scm in the lib, not whatever you'll use to package the lib itself)

setuptools_scm definitely works, but it's kinda strange to use a tool that's linked to setuptools for extracting the version

[dunamai](https://github.com/mtkennerly/dunamai) is a library that does the same with more flexibility (as far as I can tell), is less linked to a very specific way of packaging, and is expressly made to be used as a lib.

I'd say it's worth exploring :)

**Comment by webknjaz** [comment]
The reason it's currently used in the extension is that it already was a runtime dependency in sphinx docs of pylibssh so adding an extra lib for doing the same thing would be silly.

Another reason is that it has a nice mechanism of showing how far is the previous tag and showing the SCM details (name, commit + is_dirty) as a local version. It's nice to use it when the target project itself uses the same way of generating versions.

I was considering putting it into an `scm` extra rather than requiring it always.

OTOH, now that I look at it again, I realize that even having this is a feature-creep. There's already a mechanism for passing values of `version` and `release` vars from `conf.py` and if the end-user wants to have scm-based version, they'll probably have to set up it for these vars anyway and then what's left is to pass one of them to the directive.

So I guess this ticket should now be turned into a task to **remove the support for scm fallbacks**.
